version: '3'

services:
  git-server:
    build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - /share/app-data/git-server/keys:/git-server/keys
    - /share/app-data/git-server/repos:/git-server/repos

